### PR TITLE
Bumped gradle version to 5.6.4

### PR DESCRIPTION
**Pull request by casals**
Can't bump to 6.X since 'findbugs' is deprecated after 5.6.4

### CODE REVIEW

**Comment by keturn** [comment]
Would [SpotBugs](https://spotbugs.github.io/) be an acceptable substitute for findbugs? that could be another issue, though.

**Comment by casals** [comment]
> 
> 
> Would [SpotBugs](https://spotbugs.github.io/) be an acceptable substitute for findbugs? that could be another issue, though.

Actually, yes - findbugs is deprecated in gradle 6.x . I tried replacing it at first, but it also required a different config file, more changes in the script, etc - so I chose to bump the gradle version to the last one supporting findbugs for now (which solves the main problem of gradle being "too old").

**Comment by skaldarnar** [comment]
Does any of you know how the back-and-forth porting is done here in _gestalt_ - I think the change also makes sense for `develop`.

**Comment by keturn** [comment]
even with this branch, I get an error about not being able to find `findbugs`. Makes me doubt it's worth holding back on the gradle version in hopes of supporting it.

```
A problem occurred evaluating project ':gestalt'.
> Plugin with id 'findbugs' not found.
```

**Comment by casals** [comment]
Actually `FindBugs` hasn't been developed since 2015, so it's more a matter of replacing it with `SpotBugs` (which uses a different syntax for configuration) or abandoning it at all. Nevertheless, `FindBugs` is working here with Gradle 5.6.4 - I double-checked the Gradle user guide and the plugin is supported up to version 5.6.x: https://docs.gradle.org/current/userguide/upgrading_version_5.html - perhaps triple-checking it with a fresh install/someone else + changing ti to `develop` as well (as skald suggested)

**Comment by Cervator** [comment]
I did the things :-) #84 takes this a step further

**Comment by casals** [comment]
Yay!! :D

**Pull request merged**
