### PR TITLE
Possible fix problem with ProtectedDomain....

### PR DESCRIPTION
**Pull request by DarkWeird**
At least logging is added.

### CODE REVIEW

**Comment by DarkWeird** [comment]
Merge below:
https://github.com/MovingBlocks/Terasology/pull/3791

**Comment by casals** [comment]
@DarkWeird, could you please remove the commit related to the version bump? I know you did it for testing, but the extra catch should enter as a patch for 5.1.4 rather than a new minor version. Thanks!

**Comment by DarkWeird** [comment]
> @DarkWeird, could you please remove the commit related to the version bump? I know you did it for testing, but the extra catch should enter as a patch for 5.1.4 rather than a new minor version. Thanks!

@casals but last number for patches :(
And rewrite maven artifact - bad practices, expect snapshots

**Comment by casals** [comment]
> 
> 
> > @DarkWeird, could you please remove the commit related to the version bump? I know you did it for testing, but the extra catch should enter as a patch for 5.1.4 rather than a new minor version. Thanks!
> 
> @casals but last number for patches :(
> And rewrite maven artifact - bad practices, expect snapshots

not necessarily - see PR #67. other than that the modifications are OK

**Comment by DarkWeird** [comment]
> > > @DarkWeird, could you please remove the commit related to the version bump? I know you did it for testing, but the extra catch should enter as a patch for 5.1.4 rather than a new minor version. Thanks!
> > 
> > 
> > @casals but last number for patches :(
> > And rewrite maven artifact - bad practices, expect snapshots
> 
> not necessarily - see PR #67. other than that the modifications are OK

Done

**Comment by casals** [comment]
hey, @DarkWeird - sorry - I discussed it with @Cervator and we're actually bumping the version number. could you please revert the last commit? let's keep it 5.1.5 both here and in the other PR

**Pull request merged**
