### PR TITLE
gradle-6.5 --> gradle-8.2.1

### LINKED ISSUE #116: upgrade to gradle 6.9.x (prep for gradle 7.x)
Gradle 7 has some features Terasology is interested in (e.g. version catalogs). Since the MovingBlocks/✳ libraries are often used in composite builds with Terasology, it seems like a good idea to keep their gradle versions from drifting too far apart.

I propose upgrading all the libraries to the latest in the 6.x line (currently 6.9.0) and fixing whatever deprecation warnings crop up there. That should give us a smooth path to then adopting Gradle 7.

### PR DESCRIPTION
**Pull request by soloturn**
Relates to https://github.com/MovingBlocks/Terasology/pull/5109
Relates to https://github.com/MovingBlocks/Terasology/pull/4653

Closes #116

### CODE REVIEW

**Comment by jdrueckert** [comment]
There's a bunch of additional stuff that @keturn did in #136 ... we might want to consider adopting those changes, or reopening #136 and integrating the changes of this PR in there.
Edit: likely those changes are automatically generated/updated by gradle - I just don't know how to trigger that :thinking: Using gradlew after updating the version in `gradlew-wrapper.properties` didn't...

**Comment by BenjaminAmos** [comment]
The `gradlew wrapper` command updates the gradle wrapper files, including the `gradlew` and `gradlew.bat` scripts.

**Review by BenjaminAmos — CHANGES_REQUESTED** [review]
This is a good start but it fails when the Android libraries are enabled:
```
> gradlew
FAILURE: Build failed with an exception.

* Where:
Build file 'gestalt-android/build.gradle' line: 60

* What went wrong:
A problem occurred evaluating project ':gestalt-android'.
> Could not set unknown property 'classifier' for task ':gestalt-android:androidJavadocsJar' of type org.gradle.api.tasks.bundling.Jar.
```

To enable the Android libraries, you need to make sure you have the [Android SDK](https://developer.android.com/studio#command-line-tools-only) downloaded and then run `echo sdk.dir=<SDK_ROOT> > local.properties` (where `<SDK_ROOT>` is the path to the Android SDK).

**Comment by jdrueckert** [comment]
> `Could not set unknown property 'classifier' for task ':gestalt-android:androidJavadocsJar' of type org.gradle.api.tasks.bundling.Jar`

That sounds like the thing I also ran into... @BenjaminAmos made me aware of the fact that `classifier` was renamed to `archiveClassifier`

**Comment by soloturn** [comment]
thank you @jdrueckert, this error is gone now . @BenjaminAmos i set the path to the sdk and now it fails

```
❯ gradle --stacktrace
A problem occurred configuring project ':gestalt-android'.
> Failed to notify project evaluation listener.
   > org/gradle/api/plugins/MavenPlugin
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':gestalt-android'.
...
Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener.
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:111)
...
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/plugins/MavenPlugin
        at com.android.build.gradle.internal.variant.VariantHelper.setupArchivesConfig(VariantHelper.java:47)
        at com.android.build.gradle.internal.LibraryTaskManager.createBundleTask(LibraryTaskManager.java:420)
        at com.android.build.gradle.internal.LibraryTaskManager.doCreateTasksForVariant(LibraryTaskManager.java:349)
        at com.android.build.gradle.internal.TaskManager.createTasksForVariant(TaskManager.java:487)
        at com.android.build.gradle.internal.TaskManager.createTasks(TaskManager.java:405)
        at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.java:595)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:82)
        at com.android.build.gradle.internal.plugins.BasePlugin.lambda$createTasks$10(BasePlugin.java:498)
        at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt:37)
        at com.android.build.gradle.internal.crash.CrashReporting$afterEvaluate$1.execute(crash_reporting.kt)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:171)

```

i tried as well to get hints in the gradle discussion forum: https://discuss.gradle.org/t/gradle-6-8-2-gradle-8-2-1-java-lang-noclassdeffounderror-org-gradle-api-plugins-mavenplugin/46074

**Comment by BenjaminAmos** [comment]
@soloturn 
Is the Android Gradle Plugin version possibly too old now? `4.1.3` was designed to go with Gradle `6.5`, so newer versions of Gradle might have broken things. You could try updating to a newer version of the android gradle plugin, maybe `7.4.1`? It looks like versions `8.0` and above require Java 17, which isn't usable for us whilst we're still building with Java 11.
https://github.com/MovingBlocks/gestalt/blob/911728ec00a5ccf5708427599c225916d96e7ffe/build.gradle#L12-L14

**Comment by BenjaminAmos** [comment]
This was finished off by #139. Thanks @soloturn!

**Pull request merged**
